apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hbbr
  name: hbbr
  namespace: rustdesk-namespace
spec:
  containers:
    - name: hbbr
      image: rustdesk/rustdesk-server:latest
      imagePullPolicy: IfNotPresent
      command: ["hbbr"]
#      args:
#        - -k _
      ports:
        - containerPort: 21117
        - containerPort: 21119
      volumeMounts:
        - mountPath: /root
          name: hbbs-pvc
  volumes:
    - name: hbbs-pvc
      persistentVolumeClaim:
        claimName: hbbs-pvc-claim
