apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-pvc-claim
  namespace: rustdesk-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
